---
# TODO: create {{ JAILS_DIR }}/base if {{ JAILS_DIR }}/ mounted
# unarchive doesn't work with bsdtar
#- unarchive:
#    src: "{{ freebsd_base_url }}"
#    dest: {{ JAILS_DIR }}/base
#    remote_src: True

- name: Enable jail NAT
  when: jail_host_enable_nat
  block:
    - name: Clone jail interface config file
      template:
        src: rc.conf.d/network
        dest: "/etc/rc.conf.d/network"
      register: rc_conf_d_network
    - name: Clone jail interface
      command: "/etc/rc.d/netif cloneup {{ jail_host_ip4_interface }}"
      when: rc_conf_d_network.changed
    - name: Enable gateway in /etc/rc.conf.d/routing
      template:
        src: rc.conf.d/routing
        dest: "/etc/rc.conf.d/routing"
      register: rc_conf_d_routing
    - name: Restart routing to enable gateway
      service:
        name: routing
        state: restarted
      when: rc_conf_d_routing.changed

- name: Mount jails directory
  mount:
    state: mounted
    src: "{{ jail_host_dev }}"
    path: "{{ JAILS_DIR }}"
    fstype: "{{ jail_host_fstype }}"
    opts: "rw,noauto"
  register: jails_mounted

- name: Download base.txz
  get_url:
    url: "{{ jail_host_freebsd_base_url }}"
    dest: "{{ JAILS_DIR }}/base.txz"

- name: Create jail directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ JAILS_DIR }}/template/"

# Run tar manually because ansible unarchive doesn't support bsdtar
- name: Extract base.txz
  command: tar xvf "{{ JAILS_DIR }}/base.txz"
  args:
    chdir: "{{ JAILS_DIR }}/template"
    creates: "{{ JAILS_DIR }}/template/*"

- name: Install jail template rc.conf
  copy:
    src: rc.conf
    dest: "{{ JAILS_DIR }}/template/etc/"

- name: Create jails
  with_items: "{{ jail_host_jails }}"
  command: cp -a "{{ JAILS_DIR }}/template" "{{ JAILS_DIR }}/{{ item.name }}"
  args:
    creates: "{{ JAILS_DIR }}/{{ item.name }}"

- name: Copy resolv.conf to jail(s)
  with_items: "{{ jail_host_jails }}"
  copy:
    src: /etc/resolv.conf
    dest: "{{ JAILS_DIR }}/{{ item.name }}/etc/"

- name: Create jail.conf
  template:
    src: jail.conf.j2
    dest: "/etc/jail.conf"
