---
jail_host_dev: /dev/gpt/jails.eli
jail_host_ip4_interface: lo1
jail_host_ip6_interface: vtnet0
jail_host_enable_nat: true
jail_host_ip6_prefix: "fe80::"
jail_host_jails:
  - name: ns
    hostname: ns.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.2"
#:    ip6_addr: "{{ jail_host_ip6_interface }}|{{ jail_host_ip6_prefix }}::2"
  - name: web
    hostname: web.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.3"
  - name: mail
    hostname: mail.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.4"
  - name: nagios
    hostname: nagios.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.6"
    allow_raw_sockets: 1
