---
jail_host_dev: /dev/gpt/jails.eli
jail_host_ip4_interface: lo1
jail_host_ip6_interface: vtnet0
jail_host_enable_nat: true
jail_host_ip6_prefix: "fe80::"
jail_host_jails:
  - name: ns
    hostname: ns.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.2"
#:    ip6_addr: "{{ jail_host_ip6_interface }}|{{ jail_host_ip6_prefix }}::2"
  - name: web
    hostname: web.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.3"
  - name: mail
    hostname: mail.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.4"
  - name: nagios
    hostname: nagios.{{ ansible_fqdn }}
    ip4_addr: "{{ jail_host_ip4_interface}}|192.168.1.6"
    allow_raw_sockets: 1
pf_in_tcp_services_common: ssh
pf_in_udp_services_common: $mosh
pf_location: vps

pf_host_interface: vtnet0
pf_out_from: $host_interface
pf_in_to: $host_interface:0
pf_nat_main_ip4: $host_interface:0

pf_jail_lo_interface: "{{ jail_host_ip4_interface }}"
# TODO: Enable when on ipv6 capable host
#pf_enable_ipv6: true
pf_ips_dns_resolv:
  - 8.8.8.8
  - 8.8.4.4
  - 108.61.10.10
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 2001:19f0:300:1704::6
pf_ips_jails:
  - 192.168.1.0/24
